In [ ]:
# pip install pandas

Requirement already satisfied: pandas in d:\data science tranning\flask\insurance\liet\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\data science tranning\flask\insurance\liet\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# pip install numpy

Requirement already satisfied: numpy in d:\data science tranning\flask\insurance\liet\lib\site-packages (2.4.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('insurance_data.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [7]:
df

      age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
df[['gender']]

      gender
0     female
1       male
2       male
3       male
4       male
...      ...
1333    male
1334  female
1335  female
1336  female
1337  female

[1338 rows x 1 columns]

In [9]:
df['gender'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [10]:
df['children'].unique()

array([0, 1, 3, 2, 5, 4])

In [11]:
df['gender'].value_counts()

gender
male      676
female    662
Name: count, dtype: int64

In [12]:
gender_dict={
    'female':1, 'male':2
}

In [13]:
df['gender']=df['gender'].map(gender_dict)

In [14]:
df

      age  gender     bmi  children smoker     region      charges
0      19       1  27.900         0    yes  southwest  16884.92400
1      18       2  33.770         1     no  southeast   1725.55230
2      28       2  33.000         3     no  southeast   4449.46200
3      33       2  22.705         0     no  northwest  21984.47061
4      32       2  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50       2  30.970         3     no  northwest  10600.54830
1334   18       1  31.920         0     no  northeast   2205.98080
1335   18       1  36.850         0     no  southeast   1629.83350
1336   21       1  25.800         0     no  southwest   2007.94500
1337   61       1  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [15]:
df[['smoker']]

     smoker
0       yes
1        no
2        no
3        no
4        no
...     ...
1333     no
1334     no
1335     no
1336     no
1337    yes

[1338 rows x 1 columns]

In [16]:
df['smoker'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [17]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [18]:
smoker_dict={
    'yes':1, 'no':0
}

In [19]:
df['smoker']=df['smoker'].map(smoker_dict)

In [20]:
df

      age  gender     bmi  children  smoker     region      charges
0      19       1  27.900         0       1  southwest  16884.92400
1      18       2  33.770         1       0  southeast   1725.55230
2      28       2  33.000         3       0  southeast   4449.46200
3      33       2  22.705         0       0  northwest  21984.47061
4      32       2  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
1333   50       2  30.970         3       0  northwest  10600.54830
1334   18       1  31.920         0       0  northeast   2205.98080
1335   18       1  36.850         0       0  southeast   1629.83350
1336   21       1  25.800         0       0  southwest   2007.94500
1337   61       1  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [21]:
df[['region']]

         region
0     southwest
1     southeast
2     southeast
3     northwest
4     northwest
...         ...
1333  northwest
1334  northeast
1335  southeast
1336  southwest
1337  northwest

[1338 rows x 1 columns]

In [22]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [23]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [24]:
region_dict={
    'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
}

In [25]:
df['region']=df['region'].map(region_dict)

In [26]:
df

      age  gender     bmi  children  smoker  region      charges
0      19       1  27.900         0       1       1  16884.92400
1      18       2  33.770         1       0       2   1725.55230
2      28       2  33.000         3       0       2   4449.46200
3      33       2  22.705         0       0       3  21984.47061
4      32       2  28.880         0       0       3   3866.85520
...   ...     ...     ...       ...     ...     ...          ...
1333   50       2  30.970         3       0       3  10600.54830
1334   18       1  31.920         0       0       4   2205.98080
1335   18       1  36.850         0       0       2   1629.83350
1336   21       1  25.800         0       0       1   2007.94500
1337   61       1  29.070         0       1       3  29141.36030

[1338 rows x 7 columns]

In [27]:
df.isnull().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(1)

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   gender    1337 non-null   int64
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   int64
 5   region    1337 non-null   int64
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 83.6 KB

In [32]:
x=df.drop('charges',axis=1)

In [33]:
df

      age  gender     bmi  children  smoker  region      charges
0      19       1  27.900         0       1       1  16884.92400
1      18       2  33.770         1       0       2   1725.55230
2      28       2  33.000         3       0       2   4449.46200
3      33       2  22.705         0       0       3  21984.47061
4      32       2  28.880         0       0       3   3866.85520
...   ...     ...     ...       ...     ...     ...          ...
1333   50       2  30.970         3       0       3  10600.54830
1334   18       1  31.920         0       0       4   2205.98080
1335   18       1  36.850         0       0       2   1629.83350
1336   21       1  25.800         0       0       1   2007.94500
1337   61       1  29.070         0       1       3  29141.36030

[1337 rows x 7 columns]

In [34]:
x

      age  gender     bmi  children  smoker  region
0      19       1  27.900         0       1       1
1      18       2  33.770         1       0       2
2      28       2  33.000         3       0       2
3      33       2  22.705         0       0       3
4      32       2  28.880         0       0       3
...   ...     ...     ...       ...     ...     ...
1333   50       2  30.970         3       0       3
1334   18       1  31.920         0       0       4
1335   18       1  36.850         0       0       2
1336   21       1  25.800         0       0       1
1337   61       1  29.070         0       1       3

[1337 rows x 6 columns]

In [35]:
y=df[['charges']]

In [36]:
y

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1337 rows x 1 columns]

In [37]:
# df.to_csv('clean_insurance_data.csv')

In [38]:
pip install seaborn

Requirement already satisfied: seaborn in d:\data science tranning\flask\insurance\liet\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from seaborn) (2.4.3)
Requirement already satisfied: pandas>=1.2 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\data science tranning\flask\insurance\liet\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
pip install matplotlib

Requirement already satisfied: matplotlib in d:\data science tranning\flask\insurance\liet\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
pip install Scikit-Learn

Requirement already satisfied: Scikit-Learn in d:\data science tranning\flask\insurance\liet\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from Scikit-Learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from Scikit-Learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from Scikit-Learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\data science tranning\flask\insurance\liet\lib\site-packages (from Scikit-Learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
import sklearn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR
import joblib

In [42]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
lr=LinearRegression()

In [44]:
lr.fit(x_train, y_train)

LinearRegression()

In [45]:
lr.score(x_train,y_train)

0.7297182858804965

In [46]:
lr.score(x_test,y_test)

0.8068466322629111

In [47]:
pred=lr.predict(x_test)

In [48]:
pred[0:10]

array([[ 8080.45018585],
       [ 5592.87111988],
       [14378.29865472],
       [31731.81954139],
       [ 9158.3569444 ],
       [13361.01426913],
       [30257.65525771],
       [ 1308.64735626],
       [10849.42544516],
       [11375.54851897]])

In [49]:
y_test[0:10]

          charges
900    8688.85885
1064   5708.86700
1256  11436.73815
298   38746.35510
237    4463.20510
481    9304.70190
240   38511.62830
277    2150.46900
415    7345.72660
707   10264.44210

In [50]:
# df.info()

In [51]:
joblib.dump(lr,"linear_model.lb")

['linear_model.lb']

In [52]:
model=joblib.load('linear_model.lb')

In [53]:
model.predict(x_test)

array([[ 8.08045019e+03],
       [ 5.59287112e+03],
       [ 1.43782987e+04],
       [ 3.17318195e+04],
       [ 9.15835694e+03],
       [ 1.33610143e+04],
       [ 3.02576553e+04],
       [ 1.30864736e+03],
       [ 1.08494254e+04],
       [ 1.13755485e+04],
       [ 1.04822214e+04],
       [ 3.31558608e+04],
       [ 3.09123841e+04],
       [ 1.71688443e+04],
       [ 1.06361393e+04],
       [ 9.37424715e+03],
       [ 3.96524338e+03],
       [ 3.19229863e+04],
       [ 3.08468457e+03],
       [ 5.47544373e+03],
       [ 3.76844305e+03],
       [ 3.01552667e+04],
       [ 1.50768984e+04],
       [ 3.02746510e+04],
       [ 3.10830548e+04],
       [ 5.52001772e+03],
       [ 3.56655758e+04],
       [ 3.63713163e+04],
       [ 1.12979802e+04],
       [ 1.40664742e+04],
       [ 6.37519963e+03],
       [ 1.29381095e+04],
       [ 6.79284837e+02],
       [ 1.19476924e+04],
       [ 3.97832706e+04],
       [ 1.21517558e+04],
       [ 4.57717842e+03],
       [ 4.01652351e+03],
       [ 3.11475453e+04],
       [ 9.22301501e+03],
       [ 6.86852604e+03],
       [ 3.00358113e+04],
       [ 3.49732855e+04],
       [ 1.21709787e+04],
       [ 7.46262777e+03],
       [ 3.27014535e+03],
       [ 6.02195905e+03],
       [ 8.81742438e+03],
       [ 4.32171874e+03],
       [ 9.25718479e+03],
       [ 6.82679737e+03],
       [ 1.18887556e+04],
       [ 3.11350727e+04],
       [ 3.77190864e+03],
       [ 1.08474792e+04],
       [ 9.98520023e+03],
       [ 1.07454815e+04],
       [ 2.50630360e+03],
       [ 3.13486291e+04],
       [ 9.44527226e+03],
       [ 1.57668832e+04],
       [ 8.41228194e+03],
       [ 1.26377467e+04],
       [ 1.49728263e+03],
       [ 1.67511566e+04],
       [ 1.06295158e+04],
       [ 1.04219387e+04],
       [ 3.05792819e+04],
       [ 2.45776833e+04],
       [ 1.64325761e+04],
       [ 7.38210684e+03],
       [ 2.84428811e+03],
       [ 7.06992638e+03],
       [-3.29990956e+01],
       [ 1.15924890e+04],
       [-1.21951641e+03],
       [ 1.68815835e+04],
       [ 8.83059721e+03],
       [ 7.62157102e+03],
       [ 1.27175180e+04],
       [ 5.76577492e+03],
       [ 1.86978721e+04],
       [ 1.53309296e+04],
       [ 1.11806899e+04],
       [ 3.63483776e+04],
       [ 1.34071783e+04],
       [ 4.27456647e+03],
       [ 2.57056956e+03],
       [ 6.47918751e+03],
       [ 4.27749189e+03],
       [ 1.52560601e+04],
       [ 2.82268928e+04],
       [ 5.37214077e+03],
       [ 3.08592939e+03],
       [ 2.00035675e+03],
       [ 3.57507981e+04],
       [ 1.45257606e+04],
       [ 9.11985403e+03],
       [ 4.40698476e+03],
       [ 8.62880140e+03],
       [ 1.38525421e+04],
       [ 1.49580797e+04],
       [ 3.24003275e+04],
       [ 1.43680921e+04],
       [ 3.27374776e+04],
       [ 1.42320024e+02],
       [ 3.09750462e+04],
       [ 2.65864768e+04],
       [ 1.39482983e+04],
       [ 5.85231109e+03],
       [ 8.37793412e+03],
       [ 1.16365922e+04],
       [ 8.33866348e+03],
       [ 1.01084727e+04],
       [ 5.96060944e+03],
       [ 5.55786581e+03],
       [ 2.02344638e+03],
       [ 3.27438050e+03],
       [ 7.20038646e+03],
       [ 9.34232538e+03],
       [ 3.62150782e+04],
       [ 8.07973818e+03],
       [ 1.17550080e+04],
       [ 9.41521529e+03],
       [ 9.08526942e+03],
       [ 9.47332252e+03],
       [ 4.50080494e+03],
       [ 1.22296214e+04],
       [ 2.99511114e+04],
       [ 3.87490882e+04],
       [ 3.60289943e+04],
       [ 1.21149339e+04],
       [ 2.64302635e+03],
       [ 1.15458208e+04],
       [ 1.02115068e+04],
       [ 5.36684378e+03],
       [ 3.48885825e+04],
       [ 2.98098502e+04],
       [ 2.55215076e+04],
       [ 5.07298229e+03],
       [ 6.58387957e+03],
       [ 5.66505956e+03],
       [ 3.66686088e+04],
       [ 1.07790251e+04],
       [ 5.71585714e+03],
       [ 8.19481345e+03],
       [ 1.03940830e+04],
       [ 8.31592675e+03],
       [ 3.52061174e+04],
       [ 1.43138669e+04],
       [ 9.63950922e+03],
       [ 6.75703968e+03],
       [ 6.91518184e+03],
       [ 1.65709176e+04],
       [ 7.20202021e+03],
       [ 2.66062187e+04],
       [ 3.64442937e+04],
       [ 1.64908193e+04],
       [ 1.01492581e+04],
       [ 1.11207708e+04],
       [ 1.26016369e+04],
       [ 4.11467259e+03],
       [ 1.28430232e+04],
       [ 1.35966509e+04],
       [ 3.56872909e+04],
       [ 3.31848044e+04],
       [ 1.30859575e+04],
       [ 2.54290450e+04],
       [ 2.50678646e+03],
       [ 2.00467020e+03],
       [ 4.96831556e+03],
       [ 5.19658662e+03],
       [ 5.14640620e+03],
       [ 1.00234872e+04],
       [ 1.00721937e+04],
       [ 2.63490328e+04],
       [ 2.25048316e+03],
       [ 1.08369980e+04],
       [ 6.95878414e+03],
       [ 1.20177625e+04],
       [ 1.49551151e+04],
       [ 5.10897460e+03],
       [ 1.11683409e+04],
       [ 1.01405180e+04],
       [ 3.30314071e+04],
       [ 1.09390939e+04],
       [ 7.06147444e+03],
       [ 5.68599464e+03],
       [ 4.79598292e+02],
       [ 3.13195316e+04],
       [ 8.08998400e+03],
       [ 3.27799499e+04],
       [ 1.25310600e+04],
       [ 6.22173594e+03],
       [ 1.65637374e+03],
       [ 2.27715765e+03],
       [ 3.26352160e+04],
       [ 4.86982248e+03],
       [ 1.34564157e+04],
       [ 1.73527692e+04],
       [ 2.63721437e+04],
       [ 2.59829197e+04],
       [ 6.78583233e+03],
       [ 1.23754902e+04],
       [ 2.82978484e+04],
       [ 7.76646211e+03],
       [ 1.03171120e+04],
       [ 1.00958943e+04],
       [ 3.22682827e+03],
       [ 3.44859791e+04],
       [ 3.14033491e+04],
       [ 9.70862267e+03],
       [ 6.05785607e+03],
       [ 7.71103584e+03],
       [ 1.10712073e+04],
       [ 4.92149066e+03],
       [ 5.10512887e+03],
       [ 1.19149215e+04],
       [ 9.30920134e+03],
       [ 2.90368383e+03],
       [ 4.11047086e+03],
       [ 3.77140235e+04],
       [ 3.72634878e+04],
       [ 1.31316765e+04],
       [ 1.09861059e+04],
       [ 3.79416155e+04],
       [ 3.42917572e+04],
       [ 7.04424919e+03],
       [ 2.68658684e+04],
       [ 4.15529217e+03],
       [ 1.59393494e+04],
       [ 2.92782324e+04],
       [ 5.80290476e+03],
       [ 9.24780203e+03],
       [ 8.76385695e+03],
       [ 9.21451482e+03],
       [ 9.60984456e+03],
       [ 4.47445973e+03],
       [ 5.71411299e+03],
       [ 4.83231250e+03],
       [ 6.09370956e+03],
       [ 4.79405873e+03],
       [ 5.86662908e+03],
       [ 8.68043311e+03],
       [ 1.21144296e+03],
       [ 8.50633917e+03],
       [ 3.65730220e+03],
       [ 1.07277674e+04],
       [ 2.54730952e+03],
       [ 1.03284320e+04],
       [ 3.92410938e+03],
       [ 1.18221571e+04],
       [ 1.20999883e+04],
       [ 1.43976542e+04],
       [ 3.69855629e+04],
       [ 2.31239381e+04],
       [ 1.00811646e+04],
       [ 7.79937510e+03],
       [ 9.23636727e+03],
       [ 1.23969398e+04],
       [ 2.93814869e+04],
       [ 3.80711084e+04],
       [ 1.49670597e+04],
       [ 1.69526824e+04],
       [ 1.54969080e+04],
       [ 6.30338553e+03],
       [ 3.82483329e+04],
       [ 8.24687676e+03]])